"""competitor_reports

Revision ID: 5a4568830d8c
Revises: b3ae9d3104cf
Create Date: 2026-04-17 19:08:04.108102
"""
from alembic import op
import sqlalchemy as sa

revision = '5a4568830d8c'
down_revision = 'b3ae9d3104cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
