"""usage_events

Revision ID: b3ae9d3104cf
Revises: ba83680c1627
Create Date: 2026-04-17 16:44:36.932107
"""
from alembic import op
import sqlalchemy as sa

revision = 'b3ae9d3104cf'
down_revision = 'ba83680c1627'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
