"""init

Revision ID: ba83680c1627
Revises: b6de8022c357
Create Date: 2026-04-17 16:01:55.623654
"""
from alembic import op
import sqlalchemy as sa

revision = 'ba83680c1627'
down_revision = 'b6de8022c357'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
